### ISSUE TITLE
Support for presenter notes

### ISSUE THREAD

**Issue by samdmarshall** [visit1985/mdp#113]
Hi, this is a wonderful tool and I'm glad I discovered it. One feature I would like to see (and possibly contribute myself) is the ability to add notes to a slide. Specifically, I would like to add notes that aren't visible in "presentation mode" (running the markdown file through `mdp`) but clearly visible and denoted as notes when reviewing the markdown file in an editor or document viewer. I think this would be instrumental to creating more informative and helpful presentations. I've tried to use html comment syntax but that gets rendered as-is inside of `mdp`. I don't know what syntax I would propose here, maybe someone has a better idea for this.

That leads me to the more involved wish-list item I would like to see, which is speaker notes display during a presentation. Most major presentation softwares (keynote, powerpoint, etc) have functionality to display the projected slide as well as the presenter/speaker notes for that slide on a different display. I realize that this would be a major complexity change to the code to support such a feature, especially as it is operating out of a single terminal. My thought here is that a second instance of `mdp` could be run in "listener mode", where events from the primary instance (slide runner) get forwarded over to the secondary instance that could be configured to display the next slide/speaker notes for the current slide/running time/etc. This way the presenter is still operating out of a single terminal, and have access to the functionality of one of the more traditional slide-deck/presentation software.

Would love to know what your thoughts are on these suggestions, and if there is anything I could do to help with development on this.

Thanks,
Samantha

**Comment by visit1985** [comment]
I always wanted to keep mdp as small and simple as possible. The (client/server) speaker notes thing is something that doesn't fit into that concept. We would need to rewrite a big part of the software to support that. And I would rather rewrite it completely from scratch using a different language, instead of extending this codebase (which is broken by design).

However, the hidden comments thing is quite easy to implement. But we are running out of symbols that are save to use as an indicator for such comments. We should use the HTML comment syntax as you suggested. The thing is, that we need to support some layout things in the syntax, that are normally done outside of markdown (via CSS). The user must be able to easily differentiate the comments from the centering syntax. We currently use `-> <-` here.  If we want to implement comments we should find a different syntax for centering. But I have no idea what to use here at the moment.

Coming to my personal problem :grin:: I don't have time to work on enhancements of mdp at the moment. If you want to implement the hidden notes, feel free to do so and submit a pull request. I'd be happy to review it. Otherwise I'd simply leave this issue open until someone finds the time to work on it.

**Comment by samdmarshall** [comment]
Thanks for the reply, I ultimately decided that I wanted to implement this myself and writing this in C wasn't too appealing to me -- so i implemented my own system in python. I don't know if you want to keep this open or not because this is no longer an issue for me.
